Update my_page_Arsenal.html
kostyach1/Arsenal_page_HW2 pull request #1
Opened 2022-10-05 19:15 UTC by kostyach1

2022-10-05 20:37 UTC, complynx requested changes
Нужно добавить скрипт

2022-10-06 07:11 UTC, complynx commented on my_page_Arsenal.html
> +	    	x=3;
Выход переменной за границы области

2022-10-06 07:11 UTC, complynx commented on my_page_Arsenal.html
> +		foo();
Несуществующая функция.

2022-10-06 07:12 UTC, complynx commented on my_page_Arsenal.html
> +		function test() {
Функция не вызывается.

2022-10-06 12:41 UTC, complynx commented on my_page_Arsenal.html
> +	<script src="print.js"></script>
А файл где сам?

2022-10-06 12:42 UTC, kostyach1 commented on my_page_Arsenal.html
> +	<script src="print.js"></script>
в main

2022-10-06 12:47 UTC, complynx commented on my_page_Arsenal.html
> +	<script src="print.js"></script>
А почему он в main, а не здесь?
Надо было в ветку домашнего задания коммитить.

2022-10-06 12:52 UTC, kostyach1 commented on my_page_Arsenal.html
> +	<script src="print.js"></script>
закоммитил в ветку дз, извиняюсь

2022-10-06 12:58 UTC, complynx commented on print.js
> +			document.write(x);
Это не совсем хорошая процедура, и работает только в синхронных скриптах.

Но ок, принимаю.

2022-10-06 12:58 UTC, complynx commented on print.js
> +			var x=10;
Вместо var лучше использовать let

2022-10-06 12:58 UTC, complynx approved these changes

2022-10-06 12:59 UTC, kostyach1 commented on print.js
> +			document.write(x);
понял, спасибо

2022-10-06 13:03 UTC, kostyach1 commented on print.js
> +			var x=10;
принял, спасибо!

2022-10-06 13:13 UTC, merged